language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
services:
  - mongodb
notifications:
  webhooks:
    urls:
      - https://withassociates.slack.com/services/hooks/travis?token=XA3wHRF5GnTwNXN5PqWHXX8T
