language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_install:
  - "rm Gemfile.lock"
bundler_args: --without development --jobs 3 --retry 3
before_script:
  - bundle update
cache: bundler
script: bundle exec rspec spec --tag ~ci:false --color
services:
  - mongodb
sudo: false
notifications:
  webhooks:
    urls:
      secure: Ou+6h2SJnV6SFCSBM65YCOXLzvyLt4CdiTXHX6juCPjN0TAskarWq8SiUuY51coOOkJuB/hq9fICbfZafLCEranyzc8ANHc78xT84ZDZB7umgUoXcdvZhD75w9h/95eBpVIxdU8DbMuebQBkBLADv1WIZIz/auLVNC65GM7t3i4=
