language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rspec spec --tag ~ci:false --color
services:
  - mongodb
notifications:
  webhooks:
    urls:
      secure: L/M0YeNFVZ2FTkFcaHXADBWCE1p/rPrmjYsetNycpvJhvn3bo2NLtUKxA4etmwRnKXBMgmAj7F5e1dlRafZSSaem56V5HmqaWXPtpExBp+oMYUTFZsjlMsvHyqJey+TORKvAKsrYo7uKMUVgjUtbqaHI0eCt7nV8wODLQ68s87Y=
